apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: istio-test
spec:
  selector:
    app: nginx
  ports:
    - name: http-main
      port: 80
      targetPort: http-main
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-svc
  namespace: istio-test
spec:
  selector:
    app: nginx
  ports:
    - name: http-main
      port: 80
      targetPort: http-main
  type: ClusterIP
  clusterIP: None
